services:
#  caddy:

#  web:

 api:
    build: ./api
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: bank_db

 db:
    image: postgres
    restart: unless-stopped
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: ${DB_USER}
      PGUSER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 1s
      timeout: 5s
      retries: 10
